server:
  port: "${APP_LISTEN_PORT}"

spring:
  application:
    name: url-shortener
  profiles:
    active: "${APP_ENVIRONMENT}"
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  cloud:
    vault:
      uri: "${VAULT_URI}"
      token: "${URL_SHORTENER_VAULT_TOKEN}"
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
  data:
    web:
      pageable:
        max-page-size: "${URL_SHORTENER_PAGINATION_MAX_SIZE}"

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
  info:
    env:
      enabled: true
  otlp:
    metrics:
      export:
        url: "${OTLP_METRICS_ENDPOINT}"
        step: "${METRICS_SAMPLING_FREQ_IN_MIN}"
  tracing:
    sampling:
      probability: "${TRACES_SAMPLING_PROBABILITY}"
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: "${ZIPKIN_TRACES_ENDPOINT}"

internal:
  jwt:
    sign-key-path: "${URL_SHORTENER_PRIVATE_KEY_PATH}"
    verify-key-path: "${URL_SHORTENER_PUBLIC_KEY_PATH}"
    token-ttl-in-sec: "${URL_SHORTENER_TOKEN_TTL_SEC}"
  auth:
    dummy-psw-hash: "${URL_SHORTENER_BCRYPT_DUMMY_HASH}"
  host:
    external-url: "${URL_SHORTENER_EXTERNAL_URL}"

---
# Environment: LOCAL
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  cloud:
    vault:
      enabled: false

# logging:
#   level:
#     root: debug

management:
  otlp:
    metrics:
      export:
        enabled: false
  zipkin:
    tracing:
      export:
        enabled: false

---
# Environment: TEST
spring:
  config:
    activate:
      on-profile: test
